######################################################################
# Automatically generated by qmake (2.01a) Mon Jun 18 21:15:04 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += login.ui
SOURCES += main.cpp
