######################################################################
# Automatically generated by qmake (2.01a) Fri Jun 22 11:40:32 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += login.h login2.h
FORMS += login.ui
SOURCES += login.cpp main.cpp
TRANSLATIONS += login_zh.ts login.ts


CONFIG += debug
