######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 26 22:10:03 2012
######################################################################

TEMPLATE = app
TARGET = login
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += login.h
FORMS += login.ui
SOURCES += login.cpp main.cpp
TRANSLATIONS += login_zh.ts
